version: "3.8"
services:
  app:
    build: .
    ports:
        - "8081:8081"
    networks:
      - my-network

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: appdb
      MYSQL_USER: user
    ports:
      - 3307:3307
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

